# Generated by Django 4.2 on 2024-01-29 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='img_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
